baseURL = 'https://bettersaver.co.nz/'
languageCode = 'en-us'
title = 'Better Saver'
theme = "bettersaver"

[params]
    google_analitycs_id = ""
    description = "Better Saver is a website for saving money better."
    keywords = "better, saver, money, saving, budget, finance"

    site_logo = "/images/logo.svg"
    
    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    
    body_classes = "body-font bg-blue-navy"

    date_format = "2 Jan 2006"

    custom_css = [
        "bettersaver/fonts.css", 
        "bettersaver/var.css", 
        "bettersaver/colours.css",
        "bettersaver/utility.css", 
        "bettersaver/spacing.css",
        "bettersaver/base.css", 
        "bettersaver/buttons.css",
        "bettersaver/footer.css",
        
        "bettersaver/components/block-faq.css",
        "bettersaver/components/block-customer-reviews.css",
        "bettersaver/components/block-blog-recent.css",
        "bettersaver/components/block-how-it-works.css",
        "bettersaver/components/fund-finder.css",
        "bettersaver/components/site-header.css",
        "bettersaver/components/carousel.css",
        
        "bettersaver/pages/homepage.css",
        "bettersaver/pages/blog.css",
        "bettersaver/pages/contact-us.css",
        "bettersaver/pages/help.css",

        "bettersaver/display.css", # must be last
    ]

[taxonomies]
  author = 'authors'
  tags = 'tags'
  title = 'title'

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = 'tags'
    weight = 3
  [[related.indices]]
    name = 'title'
    weight = 2
  [[related.indices]]
    name = 'authors'
    weight = 1

[menus]
    [[menus.main]]
    name = "How it works"
    url = "/pages/how-it-works"
    weight = 1

    [[menus.main]]
    name = "Financial tips"
    url = "/financial-tips"
    weight = 2

    [[menus.main]]
    name = "Sign in"
    url = "https://app.bettersaver.co.nz/login/email"
    weight = 3

    [[menus.main]]
    name = "Find a fund"
    url = "https://app.bettersaver.co.nz/kiwisaver/onboarding"
    weight = 4
    [menus.main.params]
        class = "button"

    # footer left
    [[menus.footer_left]]
    name = "BetterSaver home"
    url = "/"
    weight = 1

    [[menus.footer_left]]
    name = "KiwiSaver fund advisor"
    url = "/pages/financial-tips"
    weight = 2

    [[menus.footer_left]]
    name = "How it works"
    url = "/pages/how-it-works"
    weight = 3

    [[menus.footer_left]]
    name = "Financial tips"
    url = "/financial-tips"
    weight = 4

    [[menus.footer_left]]
    name = "My account"
    url = "/pages/find-a-fund"
    weight = 5

    # footer right
    [[menus.footer_right]]
    name = "Advice disclosure"
    url = "/pages/advice-disclosure"
    weight = 1

    [[menus.footer_right]]
    name = "Terms & conditions"
    url = "/pages/terms-and-conditions"
    weight = 2

    [[menus.footer_right]]
    name = "Privacy policy"
    url = "/pages/privacy-policy"
    weight = 3

    [[menus.footer_right]]
    name = "Contact us"
    url = "/contact-us"
    weight = 4

    [[menus.footer_right]]
    name = "Help"
    url = "/help"
    weight = 5



