services:
  hugo:
    image: hugomods/hugo:exts-0.123.7
    container_name: bettersaver-hugo
    ports:
      - "1313:1313"
    volumes:
      - ..:/src
    command: server --bind 0.0.0.0 --poll 700ms
